"""
Django settings for g3 project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR.parent / '.env')
load_dotenv(BASE_DIR.parent / 'projeto.env')


def env_bool(name, default='0'):
    return os.getenv(name, default).lower() in ['true', 't', '1', 'yes', 'y']


def env_required(name):
    value = os.getenv(name)
    if not value:
        raise ImproperlyConfigured(f"{name} precisa ser definido em projeto.env.")
    return value


def postgres_database_config(require_ssl=False):
    config = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env_required('DBNAME'),
        'HOST': env_required('DBHOST'),
        'PORT': env_required('DBPORT'),
        'USER': env_required('DBUSER'),
        'PASSWORD': env_required('DBPASS'),
    }

    sslmode = os.getenv('DBSSLMODE', 'require' if require_ssl else 'disable')
    if sslmode:
        config['OPTIONS'] = {'sslmode': sslmode}

    return config


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

TARGET_ENV = os.getenv('TARGET_ENV', 'dev')
NOT_PROD = not TARGET_ENV.lower().startswith('prod')

SECRET_KEY = env_required('SECRET_KEY')
DEBUG = env_bool('DEBUG')


def env_list(name, default=''):
    value = os.getenv(name, default)

    return [
        item.strip()
        for item in value.replace(',', ' ').split()
        if item.strip()
    ]


ALLOWED_HOSTS = env_list(
    'ALLOWED_HOSTS',
    'localhost 127.0.0.1'
)

CSRF_TRUSTED_ORIGINS = env_list(
    'CSRF_TRUSTED_ORIGINS',
    'https://projeto-cyber.onrender.com'
)

render_hostname = os.getenv('RENDER_EXTERNAL_HOSTNAME')

if render_hostname and render_hostname not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(render_hostname)


if NOT_PROD:
    if env_bool('USE_POSTGRES'):
        DATABASES = {
            'default': postgres_database_config(require_ssl=False)
        }
    else:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }

    SESSION_COOKIE_SECURE = False

else:
    SECURE_SSL_REDIRECT = (
        os.getenv('SECURE_SSL_REDIRECT', '0').lower()
        in ['true', 't', '1']
    )

    SESSION_COOKIE_SECURE = SECURE_SSL_REDIRECT
    CSRF_COOKIE_SECURE = SECURE_SSL_REDIRECT

    if SECURE_SSL_REDIRECT:
        SECURE_PROXY_SSL_HEADER = (
            'HTTP_X_FORWARDED_PROTO',
            'https'
        )

        SECURE_HSTS_SECONDS = int(
            os.getenv('SECURE_HSTS_SECONDS', '31536000')
        )

        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True

    DATABASES = {
        'default': postgres_database_config(require_ssl=True)
    }
database_url = os.getenv('DATABASE_URL')
if database_url:
    DATABASES["default"] = dj_database_url.parse(database_url)
    
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps',
    "whitenoise.runserver_nostatic",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'g3.urls'

LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'home'

SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 3600
SESSION_COOKIE_HTTPONLY = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'base'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.context_processors.recaptcha',
            ],
        },
    },
]

WSGI_APPLICATION = 'g3.wsgi.application'





# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        },
    },
    {
        'NAME': 'apps.password_validators.UppercasePasswordValidator',
    },
    {
        'NAME': 'apps.password_validators.LowercasePasswordValidator',
    },
    {
        'NAME': 'apps.password_validators.NumberPasswordValidator',
    },
    {
        'NAME': 'apps.password_validators.SpecialCharacterPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'pt-BR'

TIME_ZONE = 'America/Recife'

USE_I18N = True

USE_TZ = True


# STATIC_URL = "static/"
STATIC_URL = os.environ.get('DJANGO_STATIC_URL', "/static/")
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Chave da API do Gemini usada na moderação/classificação de avaliações por IA.
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')

# Google reCAPTCHA v2 (login e cadastro), contra automação/força bruta.
# Os defaults sao as chaves de teste publicas do Google (sempre aprovam,
# validas so em localhost) - troque por chaves reais de
# https://www.google.com/recaptcha/admin antes de ir pra producao.
RECAPTCHA_SITE_KEY = os.getenv('RECAPTCHA_SITE_KEY', '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI')
RECAPTCHA_SECRET_KEY = os.getenv('RECAPTCHA_SECRET_KEY', '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe')

# Chave da criptografia SIMÉTRICA (Fernet/AES) usada para cifrar em repouso os
# dados pessoais das reservas (ver apps/crypto_fields.py). A chave vive FORA do
# banco de dados, em variável de ambiente, para que um dump do banco não seja
# suficiente para ler os dados. Gere uma chave com:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
FIELD_ENCRYPTION_KEY = os.getenv('FIELD_ENCRYPTION_KEY', '')

# Logging de eventos de segurança (login, moderação de IA, etc.)
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'security': {
            'format': '%(asctime)s [%(levelname)s] %(message)s',
        },
    },
    'handlers': {
        'security_file': {
            'class': 'logging.FileHandler',
            'filename': LOG_DIR / 'security.log',
            'formatter': 'security',
        },
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'security': {
            'handlers': ['security_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

#No arquivo settings.py do seu projeto, adicione a configuração para o envio de emails.
#Aqui está um exemplo usando o backend de email do console para fins de desenvolvimento (isso apenas imprimirá o email no console, 
#ao invés de enviá-lo):
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '25'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS')
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL')
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '10'))
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@apontecafes.local')
SERVER_EMAIL = os.getenv('SERVER_EMAIL', DEFAULT_FROM_EMAIL)

if EMAIL_USE_TLS and EMAIL_USE_SSL:
    raise ImproperlyConfigured('EMAIL_USE_TLS e EMAIL_USE_SSL nao podem estar ativos ao mesmo tempo.')
#Para produção, você substituiria isso por configurações adequadas para um servidor SMTP real. #########################################
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
