# Generated by Django 5.0.3 on 2026-09-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0046_alter_reservacafe_numero_de_pessoas'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='classificacao_ia',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='justificativa_ia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
