# Generated by Django 5.0.3 on 2026-09-13 14:37

import apps.crypto_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0048_grupo_empresarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacafe',
            name='nome_cliente',
            field=apps.crypto_fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservacafe',
            name='observacao',
            field=apps.crypto_fields.EncryptedTextField(default='Descrição não informada'),
        ),
    ]
