# Generated by Django 5.0.3 on 2026-09-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0049_alter_reservacafe_nome_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='foto_avaliacao_sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='foto_ambiente_sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usercliente',
            name='profile_image_sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
