# Generated by Django 5.0.3 on 2026-09-17 02:36

import apps.upload_paths
import apps.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0050_avaliacao_foto_avaliacao_sha256_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='foto_avaliacao',
            field=models.ImageField(blank=True, null=True, upload_to=apps.upload_paths.upload_foto_avaliacao, validators=[apps.validators.validar_conteudo_imagem]),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='foto_ambiente',
            field=models.ImageField(blank=True, null=True, upload_to=apps.upload_paths.upload_foto_ambiente, validators=[apps.validators.validar_conteudo_imagem]),
        ),
        migrations.AlterField(
            model_name='usercliente',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.upload_paths.upload_profile_image, validators=[apps.validators.validar_conteudo_imagem]),
        ),
    ]
