# Generated by Django 5.0.3 on 2026-09-17 12:28

import apps.crypto_fields
import django.core.validators
from django.db import migrations, models


def preencher_hashes_e_cifrar(apps_registry, schema_editor):
    """Calcula os campos "*_hash" (lookup/unicidade) para as linhas já
    existentes e, de brinde, cifra em repouso o valor legado em claro: como
    os campos email/cnpj/whatsapp já foram alterados para Encrypted*Field
    nas operações anteriores desta mesma migration, regravar a linha
    (.save()) passa pelo get_prep_value() do campo e cifra o valor -- mesmo
    mecanismo do comando `encrypt_existing_data`, aplicado aqui de uma vez
    para não deixar as linhas existentes pendentes até alguém rodá-lo.
    """
    Cafe = apps_registry.get_model('apps', 'Cafe')
    UserCliente = apps_registry.get_model('apps', 'UserCliente')
    calcular_hash_busca = apps.crypto_fields.calcular_hash_busca

    for cafe in Cafe.objects.all():
        cafe.cnpj_hash = calcular_hash_busca(cafe.cnpj)
        cafe.whatsapp_hash = calcular_hash_busca(cafe.whatsapp)
        cafe.save(update_fields=[
            'cnpj', 'cnpj_hash', 'whatsapp', 'whatsapp_hash',
            'email', 'endereco', 'responsavel',
        ])

    for cliente in UserCliente.objects.all():
        cliente.email_hash = calcular_hash_busca(cliente.email)
        cliente.save(update_fields=['email', 'email_hash', 'nome_completo'])


def reverter_hashes(apps_registry, schema_editor):
    """Não há nada de fato a desfazer (os valores voltam a ser lidos em
    claro pelo fallback caso os campos sejam revertidos para CharField)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0051_alter_avaliacao_foto_avaliacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercliente',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='usercliente',
            name='password',
        ),
        migrations.AddField(
            model_name='cafe',
            name='cnpj_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='cafe',
            name='whatsapp_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='usercliente',
            name='email_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=apps.crypto_fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='valor_gasto',
            field=apps.crypto_fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='cnpj',
            field=apps.crypto_fields.EncryptedCharField(default='00000000000000'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='email',
            field=apps.crypto_fields.EncryptedCharField(validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='endereco',
            field=apps.crypto_fields.EncryptedCharField(default='Endereço não informado'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='responsavel',
            field=apps.crypto_fields.EncryptedCharField(default='Nome do responsável não informado'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='whatsapp',
            field=apps.crypto_fields.EncryptedCharField(default='5500000000000'),
        ),
        migrations.AlterField(
            model_name='usercliente',
            name='email',
            field=apps.crypto_fields.EncryptedCharField(validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='usercliente',
            name='nome_completo',
            field=apps.crypto_fields.EncryptedCharField(default='Desconhecido'),
        ),
        migrations.RunPython(preencher_hashes_e_cifrar, reverter_hashes),
    ]
