# Generated by Django 5.0.3 on 2026-09-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0052_remove_usercliente_confirm_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='cnpj_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='whatsapp_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='usercliente',
            name='email_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
    ]
